# Generated by Django 4.0.8 on 2022-12-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
