# Generated by Django 4.0.8 on 2022-12-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_plant_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("kingdom", "Царство"),
                            ("phylum", "Отдел"),
                            ("class", "Класс"),
                            ("order", "Порядок"),
                            ("family", "Семейство"),
                            ("genus", "Род"),
                        ],
                        max_length=7,
                    ),
                ),
                ("title", models.CharField(max_length=127, unique=True)),
                ("latin_title", models.CharField(max_length=127, unique=True)),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="web.taxon")),
            ],
        ),
        migrations.RemoveField(
            model_name="family",
            name="order",
        ),
        migrations.RemoveField(
            model_name="genus",
            name="family",
        ),
        migrations.RemoveField(
            model_name="order",
            name="class_name",
        ),
        migrations.DeleteModel(
            name="Class",
        ),
        migrations.DeleteModel(
            name="Family",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Phylum",
        ),
        migrations.AlterField(
            model_name="plant",
            name="genus",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.taxon"),
        ),
        migrations.DeleteModel(
            name="Genus",
        ),
    ]
