# Generated by Django 4.0.8 on 2022-12-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_taxon_remove_family_order_remove_genus_family_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(max_length=320, unique=True, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="name",
            field=models.CharField(max_length=127, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="surname",
            field=models.CharField(max_length=127, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="parent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="web.taxon"),
        ),
    ]
