# Generated by Django 4.0.8 on 2022-12-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_alter_staff_email_alter_staff_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="parent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="web.taxon"),
        ),
    ]
