# Generated by Django 4.0.8 on 2022-12-29 18:28

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_taxon_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127, unique=True)),
                ("latin_title", models.CharField(max_length=127, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127, unique=True)),
                ("latin_title", models.CharField(max_length=127, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Phylum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127, unique=True)),
                ("latin_title", models.CharField(max_length=127, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="taxon",
            name="lft",
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxon",
            name="mptt_level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxon",
            name="rght",
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="taxon",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taxon",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="web.taxon",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127, unique=True)),
                ("latin_title", models.CharField(max_length=127, unique=True)),
                (
                    "class_name",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.class"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127, unique=True)),
                ("latin_title", models.CharField(max_length=127, unique=True)),
                ("family", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.family")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="family",
            name="order",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.order"),
        ),
        migrations.AddField(
            model_name="class",
            name="phylum",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.phylum"),
        ),
    ]
