# Generated by Django 4.0.8 on 2023-01-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_class_family_phylum_taxon_lft_taxon_mptt_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="order",
        ),
        migrations.RemoveField(
            model_name="genus",
            name="family",
        ),
        migrations.RemoveField(
            model_name="order",
            name="class_name",
        ),
        migrations.AlterField(
            model_name="taxon",
            name="latin_title",
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name="taxon",
            name="title",
            field=models.CharField(max_length=127),
        ),
        migrations.AlterUniqueTogether(
            name="taxon",
            unique_together={("level", "title", "latin_title")},
        ),
        migrations.DeleteModel(
            name="Class",
        ),
        migrations.DeleteModel(
            name="Family",
        ),
        migrations.DeleteModel(
            name="Genus",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Phylum",
        ),
    ]
