# Generated by Django 4.0.8 on 2023-03-01 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_remove_family_order_remove_genus_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="digitized_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="taxon",
            name="level",
            field=models.CharField(
                choices=[
                    ("genus", "Род"),
                    ("family", "Семейство"),
                    ("order", "Порядок"),
                    ("class", "Класс"),
                    ("phylum", "Отдел"),
                    ("kingdom", "Царство"),
                ],
                max_length=7,
            ),
        ),
    ]
