# Generated by Django 4.0.8 on 2023-03-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_remove_family_order_remove_genus_family_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taxon",
            name="lft",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="mptt_level",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="rght",
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="tree_id",
        ),
        migrations.AlterField(
            model_name="taxon",
            name="level",
            field=models.CharField(
                choices=[
                    ("genus", "Род"),
                    ("family", "Семейство"),
                    ("order", "Порядок"),
                    ("class", "Класс"),
                    ("phylum", "Отдел"),
                    ("kingdom", "Царство"),
                ],
                max_length=7,
            ),
        ),
    ]
