# Generated by Django 4.0.8 on 2023-03-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_remove_taxon_lft_remove_taxon_mptt_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxon",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="web.taxon",
                verbose_name="parent",
            ),
        ),
    ]
