# Generated by Django 4.0.8 on 2023-03-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_plant_digitized_at_alter_taxon_level"),
        ("web", "0009_alter_taxon_parent"),
    ]

    operations = []
