# Generated by Django 4.0.10 on 2023-05-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_merge_20230305_2250"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plant",
            options={"ordering": ("-number",)},
        ),
    ]
