# Generated by Django 4.0.10 on 2023-05-01 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_merge_20230305_2250"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordChange",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
