# Generated by Django 4.0.10 on 2023-05-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0011_alter_plant_options"),
        ("web", "0011_passwordchange"),
    ]

    operations = []
