# Generated by Django 4.0.10 on 2023-06-02 20:33

from django.db import migrations, models
from django.utils.datetime_safe import datetime


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0012_merge_0011_alter_plant_options_0011_passwordchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordchange",
            name="expired_at",
            field=models.DateTimeField(default=datetime(2023, 6, 3, 0, 33, 44, 211103)),
        ),
    ]
