version: '3'

services:
  app:
    image: soil:latest
    build:
      dockerfile: deploy/app/Dockerfile
      context: ..
    depends_on:
      - postgres
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432

  postgres:
    image: postgres:14-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: soil_db
      POSTGRES_USER: soil_user
      POSTGRES_PASSWORD: soil
    volumes:
      - "db:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db: